tests:
	SAMPLE_DATABASE_URL=jdbc:mysql://localhost:3306/sample_kotlin_app_test \
	SAMPLE_DATABASE_USERNAME=root \
	SAMPLE_DATABASE_PASSWORD= \
	SAMPLE_REDIS_HOSTNAME=localhost \
	SAMPLE_REDIS_PORT=6379 \
	SAMPLE_REDIS_PASSWORD= \
	./gradlew test

run:
	SAMPLE_DATABASE_URL=${SAMPLE_DATABASE_URL} \
	SAMPLE_DATABASE_USERNAME=${SAMPLE_DATABASE_USERNAME} \
	SAMPLE_DATABASE_PASSWORD=${SAMPLE_DATABASE_PASSWORD} \
	SAMPLE_REDIS_URL=${SAMPLE_REDIS_URL} \
	SAMPLE_REDIS_PORT=6379 \
	SAMPLE_REDIS_PASSWORD=${SAMPLE_REDIS_PASSWORD} \
	./gradlew bootRun